import type { Metadata } from 'next';
import './globals.css';
import clsx from 'clsx';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
  display: 'swap', // memastikan font konsisten antara SSR dan client
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning={true}
        className={clsx(
          poppins.variable,
          'antialiased',
          'flex',
          'justify-center',
          'bg-white'
        )}
        style={{ minHeight: '100vh' }} // pastikan tinggi konsisten
      >
        <main className='mx-auto flex min-h-screen w-full max-w-[1440px] flex-col rounded-none opacity-100 bg-white'>
          {children}
        </main>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
